# Generated by Django 4.2.7 on 2023-11-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail_address', models.EmailField(max_length=254)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
