# Generated by Django 4.2.7 on 2023-11-26 11:34

import dashboard.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailEnvoi', models.EmailField(max_length=254)),
                ('password_mailEnvoi', dashboard.fields.HashField(editable=False, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntreprise', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='received_at',
        ),
        migrations.CreateModel(
            name='emailCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.BooleanField(default=False)),
                ('form_completed', models.BooleanField(default=False)),
                #('id_campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campagne')),
                #('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
        ),
        #migrations.AddField(
          #  model_name='campagne',
            #name='id_entreprise',
            #field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.entreprise'),
        #),
        #migrations.AddField(
            #model_name='employee',
            #name='id_entreprise',
            #field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.entreprise'),
            #preserve_default=False,
        #),
    ]
