# Generated by Django 4.2.7 on 2023-11-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_campagne_entreprise_rename_name_employee_nom_and_more'),
    ]

    operations = [
        
    ]
