# Generated by Django 4.2.7 on 2023-11-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_emailcampagne_id_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='id_entreprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.entreprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailcampagne',
            name='id_campagne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.campagne'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='id_entreprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.entreprise'),
            preserve_default=False,
        ),
    ]
