# Generated by Django 4.2.7 on 2023-11-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='id_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.template'),
            preserve_default=False,
        ),
    ]
