# Generated by Django 4.2.7 on 2023-11-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20231126_1926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Entreprise',
            table='dashboard_Entreprise',
        ),
    ]
