# Generated by Django 4.2.7 on 2023-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20231126_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntreprise', models.CharField(max_length=200)),
            ],
        ),
    ]
