# Generated by Django 4.2.7 on 2023-11-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_fakeemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakeemail',
            old_name='mailEnvoi',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='fakeemail',
            old_name='password_mailEnvoi',
            new_name='password',
        ),
    ]
