# Generated by Django 4.2.7 on 2023-11-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_entreprisetest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Entreprise',
            table='dashboard_entreprise',
        ),
    ]
