# Generated by Django 4.2.7 on 2023-11-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20231126_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='id_entreprise',
        ),
        migrations.RemoveField(
            model_name='emailcampagne',
            name='id_campagne',
        ),
        migrations.RemoveField(
            model_name='emailcampagne',
            name='id_employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_entreprise',
        ),
        migrations.DeleteModel(
            name='EntrepriseTest',
        ),
        migrations.DeleteModel(
            name='campagne',
        ),
        migrations.DeleteModel(
            name='emailCampagne',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='entreprise',
        ),
    ]
