# Generated by Django 4.2.7 on 2023-11-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_campagne_password_mailenvoi_and_more'),
    ]

    operations = [
        
    ]
