# Generated by Django 4.2.7 on 2023-11-26 19:23

import dashboard.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0011_remove_campagne_id_entreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailEnvoi', models.EmailField(max_length=254)),
                ('password_mailEnvoi', dashboard.fields.HashField(editable=False, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntreprise', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('mail_address', models.EmailField(max_length=254)),
                ('id_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.BooleanField(default=False)),
                ('form_completed', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=6, validators=[django.core.validators.MaxLengthValidator(limit_value=6)])),
                ('id_campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campagne')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
        ),
        migrations.AddField(
            model_name='campagne',
            name='id_entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.entreprise'),
        ),
    ]
