# Generated by Django 4.2.7 on 2023-11-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_mailenvoi_campagne_id_mailenvoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='mailEnvoi',
        ),
    ]
