# Generated by Django 4.2.7 on 2023-11-26 20:29

import dashboard.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('password', dashboard.fields.HashField(editable=False, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='mailEnvoi',
        ),
        migrations.RemoveField(
            model_name='campagne',
            name='password_mailEnvoi',
        ),
        migrations.AddField(
            model_name='campagne',
            name='id_mailEnvoi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.fakeemail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campagne',
            name='id_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.template'),
            preserve_default=False,
        ),
    ]
