# Generated by Django 4.2.7 on 2023-11-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_campagne_id_mailenvoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='id_mailEnvoi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.fakeemail'),
            preserve_default=False,
        ),
    ]
